### ISSUE TITLE
Possible bug with target language

### ISSUE THREAD

**Issue by elyase** [ccasimiro88/TranslateAlignRetrieve#7]
Shouldn't this line:

https://github.com/ccasimiro88/TranslateAlignRetrieve/blob/9f49d67a3acc905739b5a3f92e86cc0e25fd81ef/src/tar/src/retrieve/translate_retrieve_squad_utils.py#L119

be instead:

`translation = sent_tokenize(translation, 'spanish')[0]`

**Comment by ccasimiro88** [comment]
Hi,

Yes, if you want a language-specific sentence tokenization the correct line is the one you propose.

However, as stated in the NLTK official documentation, the `nltk.tokenize.sent_tokenize` use an instance of the class `nltk.tokenize.punkt.PunktSentenceTokenizer` that works well for many European languages: https://www.nltk.org/api/nltk.tokenize.html#nltk.tokenize.punkt.PunktSentenceTokenizer

Said that I empirically checked using some examples, and the sentence tokenizer works identically for both English and Spanish with the answers translations generated by the TAR method.

However, to improve consistency and scalability to other languages, the change you propose is necessary. I suggest using this change:

`translation = sent_tokenize(translation, LANGUAGE_ISO_MAP[lang])[0]`

I'll commit the change soon, otherwise, a pull request from your side would be well accepted.

**Comment by elyase** [comment]
Thanks for your reply. I found out because I am in the process of reproducing your results for German and had some cases where `in the 10th and 11th centuries` was being correctly translated to `10. und 11. Jahrhundert` but then stripped down by the `remove_extra_text` function to `10. und 11.` because of using the English tokenizer. Forcing nltk to use the German version seems to work correctly.

**Comment by ccasimiro88** [comment]
Here's the commit: 8ebe7f4c2e5bd74717b8ae710817bc965964b2b7
